puts "The Students of Villians Academy"
puts "-----------------------------"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex Delarge"
puts "The Wicked witch of the west"
puts "Terminator"
puts "Freddie Krueger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"
puts "Overall, we have"
print 11
puts "great students"
